Stackla/stackla-widget-templates

- widgets/styles/templates/expanded-tiles/_index.scss
> UGC-19197: fix broken Expanded Tile layout

- dist/assets/svg/down-arrow-thin.svg
- package-lock.json
- widgets/storyline/templates/tile.template.tsx
- widgets/styles/partials/_icons.scss
- widgets/styles/templates/products.scss
- widgets/styles/templates/story-line-expanded/_index.scss
> UGC-19210: Story widget 3.0 expanded tile > Add to cart UI #303

- widgets/styles/templates/story-line-expanded/_index.scss
> UGC-19234: Fix bugs

- widgets/styles/templates/story-line-expanded/_index.scss
> UGC-19234: fix share-menu button zindex

- widgets/styles/templates/story-line-expanded/_index.scss
- add line clamp to inline product title and description area
- Move tags and product slider components up
> UGC-19234: UI improvement

- widgets/nightfall/_components.scss
- widgets/nightfall/widget.scss
>  UGC-19241: push the social media icon little right side

- widgets/styles/templates/story-line-expanded/_index.scss
> UGC-19234: Story expanded UI > dynamically set products position based on setting

- widgets/storyline/templates/tile.template.tsx
- widgets/styles/templates/story-line-expanded/_index.scss
- widgets/styles/templates/tile-content.scss
> UGC-19202: Implement all the appearance settings

- widgets/slider/widget.scss
> UGC-19259: update color for public tags as per design.

- widgets/styles/templates/expanded-tiles/_responsive.scss
> UGC-19265: fix scroll issue on tablet.

- widgets/styles/partials/_tile-overlay.scss
- widgets/styles/templates/expanded-tiles/_responsive.scss
- widgets/styles/templates/share-menu.scss
> UGC-19274: fix mobile responsiveness issue on Expanded Tile.

- widgets/waterfall/tile.hbs
> UGC-19258: remove unnecessary condtion from tile template

- widgets/styles/templates/products.scss
When there is one product, show full width slider view
> Fix swiper width on one product

- guides/creating-gallery-widget-by-using-the-blank-canvas-widget/_styles.scss
- guides/creating-gallery-widget-by-using-the-blank-canvas-widget/layout.hbs
- guides/creating-gallery-widget-by-using-the-blank-canvas-widget/tile.hbs
- guides/creating-gallery-widget-by-using-the-blank-canvas-widget/widget.scss
- guides/creating-gallery-widget-by-using-the-blank-canvas-widget/widget.tsx
> UGC-19335: add original files for creating gallery widget.

- widgets/shortvideo/widget.scss
- widgets/storyline/widget.scss
- widgets/styles/templates/expanded-tiles/_index.scss
- widgets/styles/templates/story-line-expanded/_index.scss
> UGC-19399: Fix mobile view issue on Stories & Short Videos widget

- widgets/shortvideo/widget.scss
- widgets/storyline/widget.scss
- widgets/styles/templates/story-line-expanded/_dimens.scss
- widgets/styles/templates/story-line-expanded/_index.scss
Improve style for expanded tiles storypage. Looks a lot nicer now vs before.
(trying to follow suit of oneractive widget where looks quite slick and well positioned).
> refactor: update max-width for story-expanded tiles and adjust dimensions

- .github/workflows/serverless/action.yml
Reverts Stackla/stackla-widget-templates#551
> Revert "refactor: remove serverless deployment step from action.yml"

- widgets/styles/templates/expanded-tiles/_index.scss
- widgets/styles/templates/expanded-tiles/_responsive.scss
- widgets/styles/templates/products.scss
- widgets/styles/templates/tags.scss
Improve responsiveness for mobile devices on widgets.
> fix: improve responsiveness

- tests/e2e/helpers/widget-helpers.ts
- tests/e2e/shared-tests/products.ts
- tests/e2e/widgets/carousel.spec.ts
- tests/e2e/widgets/grid.spec.ts
- tests/e2e/widgets/masonry.spec.ts
- tests/e2e/widgets/nightfall.spec.ts
- tests/e2e/widgets/quadrant.spec.ts
- tests/e2e/widgets/storypage.spec.ts
- tests/e2e/widgets/waterfall.spec.ts
- widgets/nightfall/_components.scss
- widgets/nightfall/products.template.tsx
- widgets/samples/products.template.tsx
- widgets/shortvideo/_tile-content-override.scss
- widgets/starter-project/products.template.tsx
- widgets/storyline/_tile-content-override.scss
- widgets/styles/templates/expanded-tiles/_index.scss
- widgets/styles/templates/expanded-tiles/_responsive.scss
- widgets/styles/templates/tile-content.scss
style: update expanded tiles styles for mobile responsiveness
add products navigation to nightfall, quadrant, storypage, and waterfall tests
> feat: add product navigation functionality in carousel, grid, masonry, nightfall, quadrant, storypage, and waterfall tests

- tests/e2e/assertions/expanded-tile.assert.ts
- tests/e2e/utilities/ugc-test.utils.ts
Check that clicking on CTA works as expected.
> test: add validation for product button URL and redirection
